function tds = wvlt_fltr(tns)

tds= wdenoise(tns,11, ...
    'Wavelet', 'fk22', ...
    'DenoisingMethod', 'SURE', ...
    'ThresholdRule', 'Soft', ...
    'NoiseEstimate', 'LevelIndependent');

end